/**
 * This file is auto-generated by Convex.
 * Run `npx convex dev` to regenerate.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as jobs from "../jobs.js";
import type * as storage from "../storage.js";
import type * as http from "../http.js";

declare const fullApi: ApiFromModules<{
  jobs: typeof jobs;
  storage: typeof storage;
  http: typeof http;
}>;

export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
