/**
 * This file is auto-generated by Convex.
 * Run `npx convex dev` to regenerate.
 *
 * This is a stub file that will be replaced when Convex is initialized.
 */

export const api = {
  jobs: {
    create: "jobs:create",
    get: "jobs:get",
    setPromptAndRun: "jobs:setPromptAndRun",
    rerun: "jobs:rerun",
    listBySession: "jobs:listBySession",
  },
  storage: {
    getUploadUrl: "storage:getUploadUrl",
    getDownloadUrl: "storage:getDownloadUrl",
    getMultipleDownloadUrls: "storage:getMultipleDownloadUrls",
  },
};

export const internal = {
  jobs: {
    triggerWorker: "jobs:triggerWorker",
    handleWorkerCallback: "jobs:handleWorkerCallback",
    setRunning: "jobs:setRunning",
    getInternal: "jobs:getInternal",
  },
  storage: {
    getDownloadUrlInternal: "storage:getDownloadUrlInternal",
  },
};
